#pragma once

#include <QUuid>

/** Property label for DATA_TAG property in datasets created by this plugin */
inline QString DATA_TAG_LABEL = "HSNE_Tag";

/**
/* Global static UUID for tagging data generated by this plugin, used for removal upon recomputation
/* Gets instantiated in HsneAnalysisPlugin::init()
*/
inline QUuid DATA_TAG;
